source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'BCommonLib', :git => 'https://github.com/baboy/BCommonLib.git'
#pod "Qiniu", "~> 7.0"
pod 'Reachability'
pod 'FMDB'
pod 'RegexKitLite'
pod 'AFNetworking'
pod 'OpenUDID'
#pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'IQKeyboardManager', '~> 3.2.1.2'
pod 'UMengAnalytics-NO-IDFA'


